name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: github-actions/.github/workflows/build-and-pack.yml@doc/Workflow_documentation
    with:
      configuration: "Release"
      do_pack: false
      is_prerelease: false
      suffix: "none"
      publish_target: "None"
    secrets: inherit
