name: Create release (from develop only!)

# Run on manual trigger only
on:
  workflow_dispatch:

jobs:
  release:
    uses: github-actions/.github/workflows/create-release.yml@doc/Workflow_documentation
    secrets: inherit
