name: Build on develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    uses: github-actions/.github/workflows/develop.yml@doc/Workflow_documentation
    with:
      do_pack: false  
    secrets: inherit
