name: Build on develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    uses: georg-eckert-zeiss/github-actions/.github/workflows/develop.yml@main
    with:
      do_pack: false  
    secrets: inherit
