# Workflow to build and publish the develop branch

name: Build on develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  develop:
    uses: georg-eckert-zeiss/github-actions/.github/workflows/develop.yml@doc/Workflow_documentation
    with:
      do_pack: false  
    secrets: inherit
