name: .NET Core Desktop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    uses: georg-eckert-zeiss/ghp/.github/workflows/test.yml@main
    with:
      configuration: "Release"
